### ISSUE TITLE
train from the scratch vs pretrain

### ISSUE THREAD

**Issue by peterant330** [cherise215/advchain#2]
It is an amazing work!

I noticed that in the paper, you first train the network with naïve data augmentation and then fine-tuning the network with this advchain method. Did you  try to train the network directly with this advchain methods without pretrain? How is the performance comparing with only naïve data augmentation?

Best

**Comment by cherise215** [comment]
Hi,

Thanks for your interest in our work. In fact, AdvChain can still work without pretraining. But we did not observe significant improvement in our experiment. In the early stage, the adversarial optimization is quite random as the network prediction is not informative to guide the optimization.  So we assume the data augmentation is something similar to random data augmentation. In our paper, we use pre-trained models mainly because we would like to save the training time, as adv data augmentation requires at least 2X time. However, you are welcome to try both in your applications. We are curious to hear your feedback.

Best wishes,
Chen
